// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    return function(dependencies) {
      return [
        '$q', '$rootScope', function($q, $rootScope) {
          var deferred;
          deferred = $q.defer();
          require(dependencies, function() {
            var initialized;
            initialized = true;
            return $rootScope.$apply(function() {
              return deferred.resolve();
            });
          });
          return deferred.promise;
        }
      ];
    };
  });

}).call(this);
